user_settings:
  years: 10
  trading_days_per_year: 252
  total_returns: true
  random_state: 44
  risk_free_rate: 0.05
  starting_portfolio_value: 100000
  factor_regression_window: 60        # Rolling window in days
  factor_targets:                     # Entities to run factor regression on
    - PORTFOLIO                       # Always include portfolio
    - TICKERS                         # Optional: include individual tickers
paths:
  portfolio_weights: data/portfolio_weights.csv
  raw_prices_output: data/yahoo_prices.csv
  recon_prices_output: data/reconstructed_prices.csv
  recon_sources_output: data/recon_sources.csv
  realized_output: data/realized_metrics.csv
  forecast_output: data/forecast_metrics.csv
  realized_rolling_output: data/rolling_metrics/realized_rolling_long.csv
  forecast_rolling_output: data/rolling_metrics/forecast_rolling_long.csv
  correlation_matrix: data/correlation_matrix.csv
  vol_contribution: data/vol_contribution.csv
  forecast_risk_contributions: data/forecast_risk_contributions.csv
  vol_sizing_output: data/vol_sizing_weights_long.csv
  runtime_info: data/runtime_info.json
  factor_returns: data/factor_returns.csv
  factor_exposures: data/factor_exposures.csv
  factor_rolling_long: data/rolling_metrics/factor_rolling_long.csv
  r2_rolling_long: data/rolling_metrics/r2_rolling_long.csv
loader:
  excel_path: ../Portfolio.xlsm
  sheet_name: Dashboard
  named_ranges:
    tickers: Portfolio_Tickers
    weights: Portfolio_Weights
    market_values: Portfolio_MarketValues
  output_file: data/portfolio_weights.csv
  versioned_output_dir: data/weights_versions/
theme_proxies:
  AI Compute & Hardware: SOXX
  Cloud Infra & SaaS: WCLD
  Cybersecurity: CIBR
  Frontier / Deep Tech: ARKX
  Disruptive / IPO Tech: ARKK
  Consumer Growth Tech: FDN
  Fintech & Crypto: ARKF
  Global & EM Tech: EMQQ
  Biotech / Genomics: ARKG
  Value / Core Holdings: ^SPX
  Energy Infrastructure: ICLN
  Crypto Exposure: BTC-USD
  Cash Equivalent: SHV
  Large Cap Exposure: ^SPX
  Tech Exposure: ^NDX
  Volatility Exposure: ^VIX
ticker_themes:
  BTC-USD: Crypto Exposure
  ETH-USD: Crypto Exposure
  QQQ: Tech Exposure
  QQQM: Tech Exposure
  SPY: Large Cap Exposure
  TQQQ: Tech Exposure
  NVDA: AI Compute & Hardware
  AMD: AI Compute & Hardware
  SMCI: AI Compute & Hardware
  QCOM: AI Compute & Hardware
  TSM: AI Compute & Hardware
  VRT: AI Compute & Hardware
  NVTS: AI Compute & Hardware
  APLD: AI Compute & Hardware
  NBIS: AI Compute & Hardware
  CRWV: AI Compute & Hardware
  SNOW: Cloud Infra & SaaS
  CRM: Cloud Infra & SaaS
  MDB: Cloud Infra & SaaS
  ORCL: Cloud Infra & SaaS
  APP: Cloud Infra & SaaS
  DOMO: Cloud Infra & SaaS
  U: Cloud Infra & SaaS
  PANW: Cybersecurity
  CRWD: Cybersecurity
  NET: Cybersecurity
  ASTS: Frontier / Deep Tech
  RKLB: Frontier / Deep Tech
  IONQ: Frontier / Deep Tech
  QBTS: Frontier / Deep Tech
  QUBT: Frontier / Deep Tech
  RGTI: Frontier / Deep Tech
  ACHR: Frontier / Deep Tech
  RDDT: Disruptive / IPO Tech
  OUST: Disruptive / IPO Tech
  DJT: Disruptive / IPO Tech
  CVNA: Disruptive / IPO Tech
  GME: Disruptive / IPO Tech
  META: Consumer Growth Tech
  GOOGL: Consumer Growth Tech
  SHOP: Consumer Growth Tech
  TSLA: Consumer Growth Tech
  UBER: Consumer Growth Tech
  ULTY: Value / Core Holdings
  BRK-B: Value / Core Holdings
  IBIT: Crypto Exposure
  SGOV: Cash Equivalent
fallback_proxy: ^NDX

factors:
  standard:
    MARKET:
      proxy: "^NDX"

    VOLATILITY:
      proxy: "^VIX"
      transform: "pct_change"  # Use "zscore" for standardized shock indicator

    RATES:
      proxy: "^TNX"
      transform: "pct_change"  # Change in 10Y rate proxy

    MOMENTUM:
      proxy: "MTUM"
      transform: "log_return"

    SIZE:
      proxy: "IWM"
      transform: "log_return"

    VALUE:
      proxy: "VLUE"
      transform: "log_return"

    QUALITY:
      proxy: "QUAL"
      transform: "log_return"

    MIN_VOL:
      proxy: "SPLV"
      transform: "log_return"

  thematic:
    AI:
      tickers:
        - NVDA
        - AVGO
        - TSM
        - PLTR
      weights: "market_cap"        # Use actual market caps if available

    MEME:
      tickers:
        - GME
        - CVNA
        - TSLA
        - AMC
        - PLTR
        - ASTS
      weights: "equal"
      normalize: true              # Apply z-scoring across tickers before combining

